language: ruby
rvm:
- 2.1
install: gem install jekyll html-proofer
script: jekyll build && htmlproof ./site
branches:
  only:
  - pages
  - master
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- echo -e "Host 108.163.203.146\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host slsapp.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_dc941821cb90_key -iv $encrypted_dc941821cb90_iv
  -in id_sls.enc -out .travis/id_sls -d
after_success:
- chmod 600 .travis/id_sls
- ssh-add .travis/id_sls
- git remote add deploy ssh://sls@slsapp.com:1234/clettenberg/blog-18.git
- git push deploy
addons:
    ssh_known_hosts:
    - 108.163.203.146
    - slsapp.com
