language: ruby
rvm: 2.3.0
install: bundle install
branches:
  only:
  - pages
  - master
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
    - echo -e "Host ssh.phx.nearlyfreespeech.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - openssl aes-256-cbc -K $encrypted_dc941821cb90_key -iv $encrypted_dc941821cb90_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar

after_success:
    - chmod 600 .travis/sloops
    - eval "$(ssh-agent -s)"
    - ssh-add .travis/sloops
    - bundle exec rake deploy
