language: ruby
rvm: 2.1
install: gem install jekyll html-proofer glynn
script: jekyll build && htmlproof ./site
branches:
  only:
  - pages
  - master
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
after_succcess:
- glynn
before_install:
- openssl aes-256-cbc -K $encrypted_dc941821cb90_key -iv $encrypted_dc941821cb90_iv
  -in _config.yml.enc -out _config.yml -d
