language: ruby
rvm: 2.1
install: gem install jekyll html-proofer glynn
script: jekyll build && htmlproof ./site
branches:
  only:
  - pages
  - master
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - FTP_USER=cacqw7_clettenberg
  - FTP_PASSWORD=zatQDDoYTUeX;ieXsZmAL@6nUQZciLNBvvwNRGvTG3apDgwEgV
after_succcess:
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa
- rake deploy
before_install:
- openssl aes-256-cbc -K $encrypted_dc941821cb90_key -iv $encrypted_dc941821cb90_iv
  -in sloops.enc -out .travis/sloops -d
- openssl aes-256-cbc -K $encrypted_dc941821cb90_key -iv $encrypted_dc941821cb90_iv
  -in Rakefile.enc -out Rakefile -d
