language: ruby
rvm: 2.1
before_script:
    - echo -e "Host ssh.phx.nearlyfreespeech.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install: gem install jekyll html-proofer
script: jekyll build && htmlproof ./site
branches:
  only:
  - pages
  - master
  - "/pages-(.*)/"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
    - openssl aes-256-cbc -K $encrypted_dc941821cb90_key -iv $encrypted_dc941821cb90_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar

addons:
    ssh_known_hosts: ssh.phx.nearlyfreespeech.net
after_success:
    - chmod 600 .travis/sloops
    - eval "$(ssh-agent -s)"
    - ssh-add .travis/sloops
    - rake deploy
