# Site settings
title: clettenberg
email: clettenberg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
      rails.coffee.coffee
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cclettenberg.com" # the base hostname & protocol for your site
twitter_username: clettenberg
github_username:  cacqw7

# Build settings
markdown: kramdown
exclude: [vendor]
